#!/usr/bin/python3

import click

from commands.run import exec_run
from commands.images import exec_images
from commands.pull import exec_pull


@click.group()
# @click.option("--cpu", default=0.1, help="CPU limitation")
def cli():
    pass


@click.command()
def images():
    exec_images()


@click.command()
@click.argument("image_name")
def pull(image_name):
    exec_pull(image_name)


# 引数はdockerコマンドの順番に準拠
@click.command(context_settings={'ignore_unknown_options': True})
@click.argument("image_name")
@click.argument("commands", nargs=-1)
@click.option("--cpu", default=None, type=float)
def run(image_name, commands, cpu):
    exec_run(
        commands=commands,
        cpu=cpu,
        image_name=image_name)


cli.add_command(images)
cli.add_command(pull)
cli.add_command(run)


if __name__ == '__main__':
    cli()
